[tool.poetry]
name = "text-dedup"
version = "0.0.15"
description = ""
authors = ["Chenghao Mou <mouchenghao@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
numpy = "1.22.3"
datasketch = "^1.5.7"
nltk = "^3.7"
torch = "^1.11.0"
simhash = "^2.1.2"
annoy = "^1.17.0"
scipy = "1.7.3"
mpire = "^2.3.5"
loguru = "^0.6.0"
tqdm = "^4.64.0"
sentencepiece = "^0.1.96"
transformers = "^4.19.2"
pandas = "^1.4.2"
typer = "^0.4.1"
datasets = "^2.2.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
coverage = "^6.3.2"
rich = "^12.4.1"
pdoc = "^12.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
