[tool.poetry]
name = "text-dedup"
version = "0.1.1"
description = "All-in-one text deduplication"
authors = ["Chenghao Mou <mouchenghao@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "text_dedup"}]

[tool.poetry.dependencies]
python = "^3.9,<3.12"
numpy = "^1.23.2"
datasketch = "^1.5.8"
torch = "^1.12.1"
annoy = "^1.17.1"
tqdm = "^4.64.1"
hydra-core = "^1.2.0"
transformers = "^4.21.2"
datasets = "^2.4.0"
sentencepiece = "^0.1.97"
redis = "^4.3.4"
rich = "^12.5.1"
mpire = "^2.6.0"
yaspin = "^2.2.0"
scipy = "1.9.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
coverage = "^6.4.4"
Sphinx = "^5.1.1"
furo = "^2022.6.21"
pre-commit = "^2.20.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
