# Configuration for SimHash benchmark on NEWS-COPY dataset

[input]
input_type = "local_hf_dataset"

[input.read_arguments]
dataset_path = "chenghao/NEWS-COPY-eval"
split = "test"

[algorithm]
algorithm_name = "simhash"
num_proc = 6
text_column = "text"
f = 64
bit_diff = 12
num_bucket = 13
ngram_size = 1
min_length = 0
check_false_positive = true
jaccard_threshold = 0.45

[output]
output_dir = "./output/benchmark_news_simhash"
save_clusters = true
keep_cluster_column = true
clean_cache = true

[debug]
enable_profiling = false
